language: node_js
sudo: false
node_js:
  - '6.9.1'

# whitelist
branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

install:
  # Check the size of caches
  - du -sh ./node_modules || true
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  # Install npm dependencies and ensure that npm cache is not stale
  - npm install

before_script:
  - npm run lint

script:
  - npm run test-linux
